### ISSUE TITLE
how to compile it on windows

### ISSUE THREAD

**Issue by fucevin** [ethereum/evmjit#111]
I want to know how to compile it on windows

**Comment by chfast** [comment]
Sorry, I missed the question.
Now it is very simple:
1. Create a folder for build (can be inside the evmjit dir).
2. In build dir: `cmake -G "Visual Studio 14 2015 Win64" ..`
3. Open created evmjit.sln in Visual Studio.

See also https://github.com/ethereum/evmjit/blob/develop/appveyor.yml.
