### ISSUE TITLE
EVM-C: rename "mode" according to official hard-fork codenames

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#117]

**Comment by axic** [comment]
This should be possible now since those "meta hardfork" EIPs are merged and thus there is an official name :)

**Comment by chfast** [comment]
Will do with the next PR. But 2 ready-to-merge PRs are waiting in the CI queue...

**Comment by axic** [comment]
```
    EVM_FRONTIER = 0,
    EVM_HOMESTEAD = 1,
    EVM_ANTI_DOS = 2,
    EVM_CLEARING = 3,
    EVM_BYZANTIUM = 4,
    EVM_CONSTANTINOPLE = 5,
```

EIPs:
- (frontier)
- homestead
- tangerine whistle ("anti-dos")
- spurious dragon ("state clearing")
- byzantium
- constantinople

I suggest `EVM_TANGERINE_WHISTLE` and `EVM_SPURIOUS_DRAGON`.

**Comment by chfast** [comment]
Is the "mode" a good name? Maybe "revision" or "standard" (as C++ standard version).

**Comment by axic** [comment]
revision sounds good to me
