### ISSUE TITLE
LLVM version bump

### ISSUE THREAD

**Issue by reagentoo** [ethereum/evmjit#136]
Please make it possible to build the project using >=LLVM-4.0.0. And also, multiple versions of LLVM can be available in the system (except if LLVM-3.x.x installed). For this reason it would be advisable to replace LLVM_DIR variable to LLVM_VERSION:
```
 if (LLVM_VERSION)
    find_package(LLVM ${LLVM_VERSION} REQUIRED CONFIG)
```
https://github.com/ethereum/evmjit/blob/develop/cmake/ProjectLLVM.cmake#L12

5.`cmake -DLLVM_VERSION=4 .. && make`
https://github.com/ethereum/evmjit/blob/develop/README.md

**Comment by chfast** [comment]
1. `LLVM_DIR` is a standard hint for `find_package`. This is needed if you have LLVM built in your own dir. So we probably need both `LLVM_DIR` and `LLVM_VERSION`.
2. Anyway, supporting more than one version of LLVM when using C++ API is hard. I plan to migrate to LLVM 4 or 5 in future, but it's hard to find time for this task.

Why do you need it anyway?

**Comment by reagentoo** [comment]
It would be desirable, that the project was guided first of all on system libraries. And I'm not saying that you need to support build with multiple versions of LLVM. But it would be nice to make a possibility to change  LLVM version in find_package. It's better for package maintainers.

**Comment by chfast** [comment]
LLVM packages from Linux distributions are pain in the ass. They never work. I don't want to touch them any more. I prefer building LLVM from source myself.

**Comment by reagentoo** [comment]
In Gentoo Linux all LLVM versions available, builds and works. Package-maintainers and the community carefully check these packages.
`sys-devel/llvm-5.0.0:5::gentoo  USE="doc libffi ncurses -debug -gold -libedit {-test}" LLVM_TARGETS="AMDGPU BPF NVPTX (X86) -AArch64 -ARM -Hexagon -Lanai -MSP430 -Mips -PowerPC -Sparc -SystemZ -XCore"`

**Comment by chfast** [comment]
Do you need any of these changes now?

I need some control over LLVM build flags. E.g. LLVM builds with zlib support what will pull zlib dependency to evmjit.

**Comment by reagentoo** [comment]
```
echo "MYCMAKEARGS=\"-DLLVM_ENABLE_ZLIB=OFF\"" >> /etc/portage/env/llvm_cmake_args
echo "sys-devel/llvm llvm_cmake_args" > /etc/portage/package.env/llvm
emerge llvm
```

**Comment by chfast** [comment]
It now uses LLVM 5.0.
