### ISSUE TITLE
EVM-C: Rename log() callback function

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#143]
The `log()` function is not declared directly (because EVM-C uses pointers to function), but the spec suggest naming the function `log()`. The name is too short and conflicts with `log()` function from some math libs. 

How about `add_log()`?

**Comment by axic** [comment]
We're considering using the keyword emit in solidity, perhaps that is also a good alternative: `emit_log`, though I am fine with `add_log` too.

**Comment by chfast** [comment]
I like `emit_log()`.

**Comment by chfast** [comment]
Oops, wrong branch :)
