### ISSUE TITLE
EVM-C: EVM_REJECTED

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#153]
Generalize `EVM_UNSUPPORTED_CODE_FORMAT` to `EVM_REJECTED`. It would mean "I can't or don't want to execute this code".

In Hera this would mean a fallback to EVM 1.0.
In EVMJIT this would mean that the code is not hot enough to bother to jit it.

**Comment by axic** [comment]
Sounds good.

**Comment by chfast** [comment]
Done in #157
