### ISSUE TITLE
Delete the master branch

### ISSUE THREAD

**Issue by axic** [ethereum/evmjit#164]
And rename `develop` to `master` :)

(Even the 0.9 release is on `develop` and not `master`.)

**Comment by axic** [comment]
ping @chfast

**Comment by axic** [comment]
pingy ping @chfast

**Comment by chfast** [comment]
How to do it correctly not to break existing PRs?

**Comment by axic** [comment]
I think they will change over, if not, it is possible to change the branch they're pointing to.

**Comment by axic** [comment]
I see you've pushed `master` to be on par with `develop`. On each PR you can click edit and change the branch they point to, once all of them are changed, `develop` can be deleted.
