### ISSUE TITLE
EVM-C: UNDEFINED and INVALID instructions

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#168]
- [ ] Rename `EVM_BAD_INSTRUCTION` -> `EVM_UNDEFINED_INSTRUCTION`.
- [ ] Add `EVM_INVALID_INSTRUCTION` for executing `0xfe`.

Discussion: https://gitter.im/ethereum/evmjit?at=5ab52fd3e4ff28713a678277

**Comment by ehildenb** [comment]
I like it!
