### ISSUE TITLE
EVM-C: naming

### ISSUE THREAD

**Issue by axic** [ethereum/evmjit#169]
Perhaps EVM-C could deserve a better name.

Full Name | Codename
-------------- | -------------
Ethereum Execution Layer Interface | execli
Ethereum Execution Interface | eei,
Ethereum Virtual Machine Interface |

**Comment by axic** [comment]
Some random proposals: 
- evmsink
- evmgate

**Comment by ehildenb** [comment]
Can we remove `evm` from name? Eventually will support ewasm as well, right?

**Comment by ehildenb** [comment]
`network-interface`?

**Comment by chfast** [comment]
EEE for Ethereum Execution Engine
or EEEP for Ethereum Execution Engine Protocol.

**Comment by axic** [comment]
triple-e-pee or e-e-e-pee? :)

**Comment by chfast** [comment]
E3P?

**Comment by ehildenb** [comment]
Here is the K version: https://github.com/kframework/evm-semantics/blob/typed-exceptions/network.md

Note that I also am trying to formalize the communication the other direction (from the client to the VM) using the `CLIENT_` status codes at the bottom.

**Comment by jakelang** [comment]
ELI for Execution Layer Interface
or EELI to prepend the name with "Ethereum"
Pronounced like the name "Eli" or just E-L-I

**Comment by chfast** [comment]
I like the ELI one.

I'd like to have something easy to pronounce and spell. EEP is too close to EIP.

Some more suggestions:

- ethgine
- protee
- pree
- oiru

**Comment by chfast** [comment]
- ethexprot
- ethexpro
- ethex
- eexei
- eexep
- ethexep

**Comment by chfast** [comment]
- etheli
- etheei
- etheep
- evmp
- evmi
- eeei

**Comment by chfast** [comment]
- proteeth :)

**Comment by gumb0** [comment]
To me ewasm is evm, too, and I like to keep "evm" in the name. `evmi` is ok

ELI or EELI are good, too

If it's `eee`, then I hope we'll have WebAssembly-based implementation called `weee`

**Comment by chfast** [comment]
Aren't all these similar to EEI (Ethereum Environment Interface) from eWASM / Hera?

**Comment by ehildenb** [comment]
@chfast are you suggesting using EEI? I like it, in my mind the EEI and the EVM-C are "dual" to each other, and (perhaps) should be combined into one spec.

**Comment by chfast** [comment]
I did not realized that EVM-C and EEI are just names of the same thing viewed from opposite sides.

**Comment by lrettig** [comment]
I'm happy with EEI or ELI (EELI), both are easy to remember and easy to pronounce.

**Comment by chfast** [comment]
After thinking about this a week, I'd go with something with "evm" in name (if no objections from @ehildenb or others). Using "evm" makes it more recognizable comparing to random sequence of EEE... 

Propositions are:

- EVMI - Ethereum Virtual Machine Interface
- EVMGATE - Ethereum Virtual Machine Gate
- EVMP - Ethereum Virtual Machine Protocol (by analogy to wayland and Xorg, but "protocol" might be confusing).

We can also introduce EEI (Ethereum Environment Interface) here as the Client-side part of the EVMx.

**Comment by ehildenb** [comment]
I suppose EVMI makes sense, in the sense that "EVM" can be thought of as "a VM which runs on the Ethereum network", and not specifically "the EVM1.0".

**Comment by lrettig** [comment]
I think EVM and ewasm are generally considered to be two different things today--e.g. I usually refer to "ewasm replacing EVM." Strictly speaking, ewasm is *not* an Ethereum virtual machine, is it?

**Comment by axic** [comment]
One could also retroactively say that "evmc" / "evm-c" stands for "EVM connector".

**Comment by chfast** [comment]
@lrettig There are 2 competing interpretations. One is "ewasm is replacing EVM", the second is "ewams is EVM 2.0 and is replacing classic EVM1". I don't believe the name here is very important to Ethereum Community. In the end only limited number of client devs will be affected by EVMC / EVMI / whatever.

**Comment by ehildenb** [comment]
I like the "keep the evmc name but change the meaning" proposal because it's the least effort and we all already know it by that name.

**Comment by axic** [comment]
I suggest to go with `EVM Connector API` (short: `EVMC` or `EVMC API`) and with a repo name of `evmc` or `evmc-api`.

Alternative long name: `EVM Client-VM Connector API`

**Comment by chfast** [comment]
Short name: EVMC
Namespace: evmc
Repo: evmc
Long name: Ethereum Client-VM Connector API

Objections?

**Comment by axic** [comment]
Sounds good.
