### ISSUE TITLE
Do not allow building on 32-bit systems

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#17]

**Comment by phonikg** [comment]
Just tried to compile cpp-etheruem on ARM device and ran into this error:

Linking CXX shared library libevmjit.so
[ 23%] Building C object libethash/CMakeFiles/ethash.dir/internal.c.o
CMakeFiles/evmjit.dir/JIT.cpp.o:JIT.cpp:function dev::evmjit::(anonymous namespace)::JITImpl::JITImpl() [clone .constprop.123]: error: undefined reference to 'LLVMInitializeARMTargetInfo'
CMakeFiles/evmjit.dir/JIT.cpp.o:JIT.cpp:function dev::evmjit::(anonymous namespace)::JITImpl::JITImpl() [clone .constprop.123]: error: undefined reference to 'LLVMInitializeARMTarget'
CMakeFiles/evmjit.dir/JIT.cpp.o:JIT.cpp:function dev::evmjit::(anonymous namespace)::JITImpl::JITImpl() [clone .constprop.123]: error: undefined reference to 'LLVMInitializeARMTargetMC'
CMakeFiles/evmjit.dir/JIT.cpp.o:JIT.cpp:function dev::evmjit::(anonymous namespace)::JITImpl::JITImpl() [clone .constprop.123]: error: undefined reference to 'LLVMInitializeARMAsmPrinter'
collect2: error: ld returned 1 exit status
evmjit/libevmjit/CMakeFiles/evmjit.dir/build.make:535: recipe for target 'evmjit/libevmjit/libevmjit.so.0.9.0' failed
make[2]: *** [evmjit/libevmjit/libevmjit.so.0.9.0] Error 1
CMakeFiles/Makefile2:128: recipe for target 'evmjit/libevmjit/CMakeFiles/evmjit.dir/all' failed
make[1]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by phonikg** [comment]
^^^Unsure if this belongs here or under cpp-ethereum issues^^^

**Comment by chfast** [comment]
In general I never tried building on ARM. Looks like cmake misconfiguration. Can you create a separated issue?

**Comment by phonikg** [comment]
So I received a suggestion from EthDEV member to simply 'cmake -DEVMJIT=off'

This solution worked by I believe simply not trying to build the evmjit
portion at all.

**Comment by chfast** [comment]
Yes, JIT can be disabled.

I don't expect JIT to work correctly on ARM.

**Comment by phonikg** [comment]
Fair enough... thanks for your reply!
