### ISSUE TITLE
Why do I failed building the tests/test-evmjit-standalone.c?

### ISSUE THREAD

**Issue by 0xcc-Since2016** [ethereum/evmjit#171]
After I successfully build the libevmjit , I tried to build the test-evmjit-standalone.c to print out banner info under tests/ folder. But I tried whatever I can just failed it...

**Comment by chfast** [comment]
Logs?

**Comment by 0xcc-Since2016** [comment]
Sorry.. Due to my foolish and as a greenhand I didn't add -ldl & -lpthread..
with the underline script
#!/bin/sh
g++ $1 ../build/libevmjit/libevmjit-standalone-thin.a -ldl -lpthread 
everything appears just be fine.
