### ISSUE TITLE
C abi is incomplete and incompatible with languages using non-default memory allocators.

### ISSUE THREAD

**Issue by debris** [ethereum/evmjit#22]
There are issues with using C abi with languages (eg. Rust) with different memory allocators (jemalloc). Structures being used by C++ code must be allocated by C++ memory allocator. eg. `RuntimeData`.

Here is an example of fixed C abi which is succesfully being used with Rust ethereum implementation.

https://github.com/ethcore/evmjit/blob/develop/include/evmjit/JIT-c.h

**Comment by chfast** [comment]
Agreed. That was mistake.

**Comment by chfast** [comment]
I'm not sure C++ cares how the struct was allocated. C++ only cares if the pointer is valid.

**Comment by chfast** [comment]
This shows how you can create a struct matching C struct in Rust and pass a pointer to it to a C function.

**Comment by chfast** [comment]
@debris Any comments?

**Comment by debris** [comment]
> I'm not sure C++ cares how the struct was allocated. C++ only cares if the pointer is valid.

You are right. I've created a playground with a [few examples](https://github.com/debris/rust-cpp-bridge/blob/master/src/lib.rs) and everything is working fine.*

*There is one [failing test](https://github.com/debris/rust-cpp-bridge/blob/master/src/lib.rs#L88), but it is related with rust not casting ffi call argument to a reference automatically, rather than memory allocation.

**Comment by bobsummerwill** [comment]
Yes, memory-is-memory.   It doesn't matter where it came from when you are just using it.

Where allocations happened obviously do matter when you get to the deallocations.   That is a common source of issues:

- trying to deallocate on different threads
- trying to deallocate with C++ pointers with free()
- or worse!

**Comment by chfast** [comment]
Let know if you need any changes in the area.
