### ISSUE TITLE
Configure build server

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#28]
- [ ] Any working build server that just builds the code. [CircleCI](https://circleci.com/gh/ethereum/evmjit) has been configured to build every git push (including PRs).
- [ ] Configure Jenkins to build (and test if tests included) on multiple platforms. This requires LLVM being available for those platforms. Suggested solution is to use Jenkins Pipeline plugin and _Jenkinsfile_.
- [ ] _Optional_. Configure build and test of _dependent_ projects (e.g. libethereum) to be used as integration tests. This is optional because alternatively we can postpone integration tests to the moment when evmjit upgrade is proposed to dependent projects in form of a PR.

**Comment by bobsummerwill** [comment]
Please could you elaborate on this in the description above?   Thanks!
Just adding a project to Jenkins for building `evmjit` repo standalone?   Well, PRs for it, if we're following the same pattern as everything else.

**Comment by chriseth** [comment]
We considered using travis before but came to the conclusion that their capacity is not large enough to handle c++ projects, build times are too long. Why is jenkins not suitable?

**Comment by bobsummerwill** [comment]
It is our Jenkins mis-configuration which is the problem, @chriseth, especially for cross-repo changes.    It is plain broken.

But with `evmjit` repo being at the bottom of the stack, that shouldn't be an issue, should it?   Maybe we can even just add a `evmjit-prs` project, using the same template as everything else, and it will "just work"?

**Comment by chfast** [comment]
CircleCI configured: https://circleci.com/gh/ethereum/evmjit.

**Comment by bobsummerwill** [comment]
Have you set up a Github PR webhook for this yet?    If not, you should :-)

**Comment by chfast** [comment]
It should be on. I mostly have done it to check how difficult it is.
Do we want also build with Jenkins?

**Comment by bobsummerwill** [comment]
Yes.

We should build everything in Jenkins, as our primary workflow.

And we can experiment with CircleCI, TravisCI, Appveyor and buildbot (and whatever else) on the side.

**Comment by bobsummerwill** [comment]
My hope is that we can pretty much ditch the scripts after the repo reorg.    Or at least, they would go down to be exceedingly simple (and with no hard-coded sub-module info), and only be used as the "steps" in all our automation solutions.

**Comment by chfast** [comment]
@chriseth I can config Jenkins later on. I would like to start from scratch if possible to avoid using building scripts.

**Comment by chfast** [comment]
I've updated the description to make it in steps. Give :+1: if you agree.

How much of it should be done in [domesticus](https://github.com/ethereum/evmjit/milestones/domesticus)?

**Comment by chriseth** [comment]
domesticus ends tomorrow, so I would say nothing. we re-plan on monday.

**Comment by chriseth** [comment]
Result of discussion: build and test evmjit in isolation (no tests yet) and run the evmjit-tests in libethereum only when libethereum updates the evmjit version.

**Comment by chriseth** [comment]
Basic jenkins setup: http://52.28.164.97/job/build-evmjit/
build seems to only work on ubuntu now
if PRs are picked up by the webhook needs to be tested

**Comment by chfast** [comment]
It's building some old code.

**Comment by chriseth** [comment]
I think it built some old pull requests.

**Comment by chfast** [comment]
Jenkins/Windows build fixed. OSX fails: http://52.28.164.97/job/build-evmjit/evmjit=macosx_yosemite/28/console.

**Comment by bobsummerwill** [comment]
And the OS X issue is resolved too now, right, @chfast?
That was the permissions issue which @chriseth fixed.   Correct?

**Comment by chfast** [comment]
OSX fixed.
