### ISSUE TITLE
Integrate evmjit into py-ethereum (and possibly go-ethereum)

### ISSUE THREAD

**Issue by chriseth** [ethereum/evmjit#29]
It might be considered to create a separate execution context / process for evmjit to limit the effects of possible breakouts.

Moved from https://github.com/ethereum/webthree-umbrella/issues/175

**Comment by axic** [comment]
Was there any progress made on this?

**Comment by axic** [comment]
Possible a node.js binding could also be written.

**Comment by axic** [comment]
Tracked in https://github.com/ethereum/evmc/issues/100 and https://github.com/ethereum/evmc/issues/101.
