### ISSUE TITLE
Report llvm-3.8-dev package broken

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#42]

**Comment by bobsummerwill** [comment]
What platform is this for, and in what way it is broken?   Thanks!

**Comment by chfast** [comment]
Ubuntu/Debian

**Comment by bobsummerwill** [comment]
That package doesn't build?    Our code is broken when built against it?

What's the exact issue?

**Comment by chfast** [comment]
CMake shared files of llvm-3.8-dev are incorrect and build configuration of evmjit will fail. It is known issue but the maintainer is fixing it for years...

I fixed some of the issues some time ago, but I don't have direct access to the deb package SVN.

**Comment by bobsummerwill** [comment]
Blergh ...
