### ISSUE TITLE
Make fails in Fedora 23 because of different location of static llvm libraries

### ISSUE THREAD

**Issue by giacecco** [ethereum/evmjit#58]
Static ```llvm``` libraries in Fedora 23, installed from packages such as ```llvm-static.x86_64```, are in ```/usr/lib64/llvm/```, but the current ```Makefile``` looks for them in ```/usr/lib/```.

```
[giacecco@giaceccos-linux evmjit]$ mkdir build
[giacecco@giaceccos-linux evmjit]$ cd build/
[giacecco@giaceccos-linux build]$ cmake ..
-- The CXX compiler identification is GNU 5.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- EVM JIT 0.9.0
-- Using LLVM 3.7.0 (/usr/share/llvm/cmake)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/giacecco/Documents/Dico.im/GitHub-projects/evmjit/build
[giacecco@giaceccos-linux build]$ make 
Scanning dependencies of target evmjit
[  5%] Building CXX object libevmjit/CMakeFiles/evmjit.dir/JIT.cpp.o
(...)
[ 95%] Building CXX object libevmjit/CMakeFiles/evmjit.dir/support/Path.cpp.o
make[2]: *** No rule to make target '/usr/lib/libLLVMCore.a', needed by 'libevmjit/libevmjit.so.0.9.0.2'.  Stop.
CMakeFiles/Makefile2:85: recipe for target 'libevmjit/CMakeFiles/evmjit.dir/all' failed
make[1]: *** [libevmjit/CMakeFiles/evmjit.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[giacecco@giaceccos-linux build]$
```

See also https://github.com/ethereum/webthree-umbrella/issues/524 .

Thanks!

**Comment by chfast** [comment]
As I said in other issue, I can do much about broken packages of LLVM (usually binaries and executables are fine, but cmake matadata is broken). We have issues with them on multiple platforms and with multiple version of LLVM.

What you can do now is to build LLVM from source (this is the default since #64). Just make sure the cmake's option `LLVM_DIR` is not set.

**Comment by chfast** [comment]
For some time evmjit project is able to build LLVM by itself. It makes the build much longer ~20-30 mins but taking into account additional time that new user would need to spent on figuring out how to install LLVM packages on ones system it is not so bad. And it Always Works™.

Building with prebuilt LLVM is also possible, but for advanced users :).
