### ISSUE TITLE
CMake minimum version?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/evmjit#63]
During @programonauta work on getting cpp-ethereum building on Debian 8 (Jesse), he's seeing the following build break:

    CMake Error at libethereum/evmjit/CMakeLists.txt:5 (cmake_policy):
      Policy "CMP0054" is not known to this version of CMake.

Google tells me that CMP0054 was introduced in CMake 3.1.

https://cmake.org/cmake/help/v3.1/policy/CMP0054.html

In various parts of our documentation, I have seen our minimum version for CMake listed as 3.0.

Now we could obviously say "Our minimum CMake version is 3.1", but I think this one place is probably the only use we have of a > 3.0 feature, so maybe we can weaken it off, or do something conditional so that we just work out of the box on Debian.

What do you guys think?   @chfast, @chriseth?

**Comment by chfast** [comment]
Just a bug. I assumed that cmake will ignore policies it does not know. The solution would be to enclose that with version checking code. What a mess....

**Comment by chfast** [comment]
I've just found the canonical solution. I will fix that.
https://cmake.org/Wiki/CMake/Policies#Supporting_Multiple_CMake_Versions

**Comment by chfast** [comment]
Fixed here be not included in libethereum. Update the submodule there if you need it know or will come with next update later on.

**Comment by programonauta** [comment]
Thanks @chfast I changed locally and worked fine!
