### ISSUE TITLE
EVM-C: split out the interface its own module

### ISSUE THREAD

**Issue by axic** [ethereum/evmjit#82]
I propose the name `evm-c-api` (ethereum/evm-c-api).

It should contain:
- `evm.h`
- examples
  - capi
  - examplevm
- generated documentation
- validation toolkit: I see this as a simple consumer implementation which has a JSON configuration for inputs and expected output.

(Here was an earlier filtered out branch I did: https://github.com/axic/evm-c-api. I can redo the filtering later when we have a stable checkpoint.)

**Comment by chriseth** [comment]
The documentation for this api could go to github.com/ethereum/interfaces

**Comment by bobsummerwill** [comment]
What is http://github.com/ethereum/interfaces, BTW?   That is new.

What is the plan?

**Comment by chriseth** [comment]
Updated the readme: https://github.com/ethereum/interfaces/blob/master/README.md

**Comment by chfast** [comment]
I created ethereum/evmc for this :)

**Comment by axic** [comment]
Depends on #169.

**Comment by axic** [comment]
```
$ git filter-branch -f --tree-filter 'rm -rf <path>' --prune-empty HEAD
```

Did the following filter-branch and pushed here https://github.com/axic/evmc (will remove this repo):
- `libevmjit`
- `include/evmjit.h`
- `include/evmjit/JIT.h`

**Comment by chfast** [comment]
Remove also:
- cmake/
- docker/
- scripts/
- tests/
- .clang-format 
- README.md  (nothing about EVMC there, no point of keeping the history)
- CMakeLists.txt (I will have to change almost all of it anyway)
- .travis.yml
- appveyor.yml
- circleci.yml
- wercker.yml

**Comment by axic** [comment]
In the end I had to remove also:
- evmcc
- include/evmjit
- libevmjit-cpp

**Comment by axic** [comment]
Pushed the hopefully final version to: https://github.com/ethereum/evmc

**Comment by axic** [comment]
The final commandline to reproduce the same would be:
```
$ git filter-branch -f --tree-filter 'rm -rf cmake docker scripts tests libevmjit libevmjit-cpp evmcc include/evmjit include/evmjit.h README.md CMakeLists.txt .travis.yml appveyor.yml circle.yml wercker.yml' --prune-empty HEAD
```
