### ISSUE TITLE
EVM-C: Support for VM tracing

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#85]

**Comment by axic** [comment]
Do you have any idea about this yet?

**Comment by chfast** [comment]
What the other said is to use similar scheme we have in cpp-ethereum -- call a callback provided by the user every instruction.

**Comment by axic** [comment]
@chfast What will that callback return? Is it after or before every instruction?

**Comment by axic** [comment]
@chfast Is this the last thing on the table?

**Comment by chfast** [comment]
Yes. I think we need it now to be allowed moving C++ EVM to EVM-C API.

I requested a spec for the VM trace data: https://github.com/ethereum/tests/issues/249#issuecomment-323344836.

**Comment by axic** [comment]
I think an easy solution would be adding an option to `instance.set_option` (say key "tracing" with value "true" to enable it) and have a callback in `context.emit_trace`?

**Comment by axic** [comment]
Moved to https://github.com/ethereum/evmc/issues/22
