### ISSUE TITLE
EVM-C tweaks

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#88]
- [ ] Flatten `struct evm_hash256` to be an union or struct with single member and alignment specified.
- [ ] Move `code_hash` parameter of `evm_prepare_code()` before `code` parameter. That would match other functions.

**Comment by chfast** [comment]
@axic @RomanZacharia can you review this issue? Should I address anything more?

**Comment by axic** [comment]
> Move code_hash parameter of evm_prepare_code() before code parameter. That would match other functions.

:+1:

**Comment by axic** [comment]
Issue #86 should be addressed too.
