### ISSUE TITLE
EVM-C: Pass 256-bit integers as bytes

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#91]
## Currently

EVM-C API distinguish 256-bit hashes and 256-bit integers. 
- A hash is a series of 32-bytes sometimes referred as big endian integer. They are used (usually) to transfer arguments not being interpreter by the user as an integer like block hashes, addresses, etc.
- An integer is a 32-byte struct representing **host endian** (read: little endian) unsigned integer. Used to transfer arguments interpreted as numbers like value, balance, difficulty, etc.

The VM implementations has to interpret everything as an integer and converts both hashes and integers to its internal bigint representation. In some implementations, internal bigint representation matches host endian integer of EVM-C and conversion has no cost.

## Proposal

The proposal is to use only hashes/big endian representation of integers for EVM-C arguments. The name of the type is to be decided later.

## Pros
- Higher consistency of the API.
- Suitable for programming languages having trouble detecting host endianness.

## Cons
- Sub-optimal in some cases -- chain of conversion: (user integer representation -> big endian int -> host endian int) instead of (user integer representation -> host endian int).
- More complex conversion algorithms on the user side.

**Comment by chriseth** [comment]
I was actually not aware that the interface depended on the endianness of the host. As byte order conversion is extremely cheap, I would not see this as a con.

*thumbsup*

**Comment by axic** [comment]
As we discussed on the channel, big endian seems to be the best choice as the majority of bignum libraries would serialise to big endian. And pyethereum only supports big endian.

On the other hand, taking the majority of clients will run on little endian CPUs and both evmjit and hera need it in little endian, it might be worth considering making the interface little endian.

**Comment by chfast** [comment]
@axic all little endian will confuse everyone trying to pass block header :). If no objections until tomorrow I will make the change then.

**Comment by chfast** [comment]
Is the `evm_uint256be` a good name?

**Comment by gcolvin** [comment]
@chriseth what is the extremely cheap way of converting big-endian to native order?  The only portable way I know is a loop of | and <<?  It hurts bad at the level of pushing constants on the VM stack, but probably not so much here.

**Comment by chriseth** [comment]
@gcolvin if considered as part of the VM startup, this is extremely cheap I would say.

**Comment by gcolvin** [comment]
Agreed @chriseth  "cheap" is always relative.  But was hoping you knew of a trick I didn't.
