### ISSUE TITLE
EVM-C: consider renaming block and tx level query keys

### ISSUE THREAD

**Issue by axic** [ethereum/evmjit#94]
Especially `GAS_LIMIT` as that is block level and hopefully there'll be a transaction level gas limit opcode in the future.

In eWASM we have [every key prefixed](https://github.com/ethereum/evm2.0-design/blob/master/eth_interface.md#api).

**Comment by chfast** [comment]
I directly mapped the names from opcodes names, but that make sense.

**Comment by chfast** [comment]
@axic Do you want me to do it?

**Comment by axic** [comment]
@chfast I can look into it during my flights or next week

**Comment by axic** [comment]
This was done as part of #112.
